languageCode = "en-us"
title = "Bing's Note"
baseurl = "http://note.fadeinout.bid/"
copyright = "All rights reserved - 2017"
disqusshortname = "fadebin"
paginate = 5
# pluralizelisttitles = false
theme = "casper"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "Posts"
url = "/post"
weight = 11
[[menu.main]]
name = "About"
url = "/about"
weight = 12
[[menu.main]]
name = "Github repos"
pre = "<h6>Follow me</h6>"
url = "https://github.com/fadebin"
weight = 100

[params]
  description = "分享软件、学习以及各种有趣的事."
  cover = "images/cover.jpg"
  author = "Bing"
  authorname = "Bing"
  authorlogo = "images/profile.jpg"
  authorlocation = "Chengdu, China"
  authorwebsite = "http://fadeinout.bid"
  bio= "IT software Engineer, Open source enthusiast, Pythonista."
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "fadebin"
  # twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  #[params.social]
  #  twitter = "your_twitter"